name: Ryan Laffoon
markdown: kramdown
collections:
  nav:
    output: true
  projects:
    output: true
    permalink: /projects/:title/
  employers:
    output: true
    permalink: /employers/:title/
