me:
 name:
  first: Ryan
  last: Laffoon
  middle: Todd
  suffix: Sr
 contact:
  address:
   street: 20812 52nd Ave W
   city: Lynnwood
   state: WA
   zip: 98036
   country: USA
  social:
   twitter: ryan_laffoon
   pinterest: ryanlaffoon
   github: ryanlaffoon
   linkedin: ryan-laffoon
   stackoverflow: ryanlaffoon
  phone:
   cell: (509) 290-1865
  email: ryan_laffoon@msn.com
  bio:
   gender: Male
   birthdate: 1983-05-19
 image-url: ryan.jpg
