me:
 name:
  first: "Ryan"
  last: "Laffoon"
  middle: "Todd"
 contact:
  social:
   github: "ryanlaffoon"
   linkedin: "ryan-laffoon"
   stackoverflow: "ryanlaffoon"
  email: "ryan_laffoon@msn.com"
  bio:
   gender: "Male"
   birthdate: 1983-05-19
 image-url: "/img/ryan.jpg"
 lead: "Hi, I'm Ryan Laffoon! I'm a software developer from Seattle, and I've been building web applications and services since 2000!"
 intros: 
  - "I love technology & I'm excited by the creative and collaborative process of software development. I created this site in order to showcase some of the work I've done and share some of that excitement."
  - "Please feel free to check out my <a href='/cv/'>Credentials</a>, browse through some <a href='/projects'>Projects</a> I've worked on, dive into my background <a href='/companies/'>Experience</a> & <a href='/colleges/'>Education</a>."
  - "I am currently seeking opportunities to build software with excellent people. Please <a href='contact'>get in contact with me</a> if you're interested in working together."
